name: 'GitHub Action for SwiftLint'
description: 'A tool to enforce Swift style and conventions'
author: 'step-security'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'shield'
  color: 'orange'
