name: 'GitHub Action for SwiftLint'
description: 'A tool to enforce Swift style and conventions'
author: 'step-security'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/step-security/action-swiftlint:v3.2.2@sha256:3dc7432df15c4ed239c605a1d43d9f6dfceb70e80db7347f84f655be90ade254' #v3.2.2
branding:
  icon: 'shield'
  color: 'orange'
